name: arcade_api
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.2

dependencies:
  arcade_repository:
    path: C:/Users/Diessy/IdeaProjects/arcade_repository

  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_plus: ^1.9.2
  shelf_multipart: ^1.0.0
  get_it: ^7.7.0
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
