name: arcade_api
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.2

dependencies:
  objectbox: ^2.5.1
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_plus: ^1.9.2
  shelf_multipart: ^1.0.0
  http: ^1.1.0
  get_it: ^7.7.0
  dart_jsonwebtoken: ^2.14.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.0.0
  objectbox_generator: any
