// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'models/event.dart';
import 'models/marker.dart';
import 'models/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3641625309124856740),
      name: 'Event',
      lastPropertyId: const obx_int.IdUid(8, 7917345948453636044),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 17633517628885872),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2881814261958305759),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7588564157234731435),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3712613966648961507),
            name: 'eventType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4936638773886025982),
            name: 'markerId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 4414900424959485281),
            relationTarget: 'Marker'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1857614491159167328),
            name: 'createdById',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 2797459950233595612),
            relationTarget: 'User'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7917345948453636044),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4413450018317746965),
      name: 'Marker',
      lastPropertyId: const obx_int.IdUid(4, 8532013014470610344),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3873186835549286795),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7810051586961322896),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3795493444501182286),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8532013014470610344),
            name: 'altitude',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5245049771408831401),
      name: 'User',
      lastPropertyId: const obx_int.IdUid(7, 8008839518377418486),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2556912492356042669),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1202881106797085830),
            name: 'identifier',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 7911329766454026192)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8723107177053627186),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5921526977577780009),
            name: 'banned',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 964990750158744153),
            name: 'manager',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) {
  return obx.Store(getObjectBoxModel(),
      directory: directory,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 5245049771408831401),
      lastIndexId: const obx_int.IdUid(3, 7911329766454026192),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        2477026663232477285,
        8008839518377418486,
        679178013217149710
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Event: obx_int.EntityDefinition<Event>(
        model: _entities[0],
        toOneRelations: (Event object) => [object.marker, object.createdBy],
        toManyRelations: (Event object) => {},
        getId: (Event object) => object.id,
        setId: (Event object, int id) {
          object.id = id;
        },
        objectToFB: (Event object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          final eventTypeOffset = fbb.writeString(object.eventType);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addOffset(4, eventTypeOffset);
          fbb.addInt64(5, object.marker.targetId);
          fbb.addInt64(6, object.createdBy.targetId);
          fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Event()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..description = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..eventType = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          object.marker.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.marker.attach(store);
          object.createdBy.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.createdBy.attach(store);
          return object;
        }),
    Marker: obx_int.EntityDefinition<Marker>(
        model: _entities[1],
        toOneRelations: (Marker object) => [],
        toManyRelations: (Marker object) => {},
        getId: (Marker object) => object.id,
        setId: (Marker object, int id) {
          object.id = id;
        },
        objectToFB: (Marker object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.latitude);
          fbb.addFloat64(2, object.longitude);
          fbb.addFloat64(3, object.altitude);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Marker()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..latitude =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0)
            ..longitude =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..altitude =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);

          return object;
        }),
    User: obx_int.EntityDefinition<User>(
        model: _entities[2],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final identifierOffset = fbb.writeString(object.identifier);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, identifierOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addBool(3, object.banned);
          fbb.addBool(4, object.manager);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..identifier = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..banned =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false)
            ..manager =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Event] entity fields to define ObjectBox queries.
class Event_ {
  /// see [Event.id]
  static final id = obx.QueryIntegerProperty<Event>(_entities[0].properties[0]);

  /// see [Event.name]
  static final name =
      obx.QueryStringProperty<Event>(_entities[0].properties[1]);

  /// see [Event.description]
  static final description =
      obx.QueryStringProperty<Event>(_entities[0].properties[2]);

  /// see [Event.eventType]
  static final eventType =
      obx.QueryStringProperty<Event>(_entities[0].properties[3]);

  /// see [Event.marker]
  static final marker =
      obx.QueryRelationToOne<Event, Marker>(_entities[0].properties[4]);

  /// see [Event.createdBy]
  static final createdBy =
      obx.QueryRelationToOne<Event, User>(_entities[0].properties[5]);

  /// see [Event.createdAt]
  static final createdAt =
      obx.QueryDateProperty<Event>(_entities[0].properties[6]);
}

/// [Marker] entity fields to define ObjectBox queries.
class Marker_ {
  /// see [Marker.id]
  static final id =
      obx.QueryIntegerProperty<Marker>(_entities[1].properties[0]);

  /// see [Marker.latitude]
  static final latitude =
      obx.QueryDoubleProperty<Marker>(_entities[1].properties[1]);

  /// see [Marker.longitude]
  static final longitude =
      obx.QueryDoubleProperty<Marker>(_entities[1].properties[2]);

  /// see [Marker.altitude]
  static final altitude =
      obx.QueryDoubleProperty<Marker>(_entities[1].properties[3]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.id]
  static final id = obx.QueryIntegerProperty<User>(_entities[2].properties[0]);

  /// see [User.identifier]
  static final identifier =
      obx.QueryStringProperty<User>(_entities[2].properties[1]);

  /// see [User.name]
  static final name = obx.QueryStringProperty<User>(_entities[2].properties[2]);

  /// see [User.banned]
  static final banned =
      obx.QueryBooleanProperty<User>(_entities[2].properties[3]);

  /// see [User.manager]
  static final manager =
      obx.QueryBooleanProperty<User>(_entities[2].properties[4]);
}
